### ISSUE TITLE
EC EKS TLS Plugin exiting

### ISSUE THREAD

**Issue by simran3695** [EC-Release/oci#123]
We have seen issues where are plg getsloaded and then immediatley get exited and also after logging to the backedn we sae the plugins.yaml is not updating the schema and hostname parameters.

And the conectivity and tls logs are as below:

![image](https://user-images.githubusercontent.com/65241877/102257920-5b258680-3f33-11eb-98ce-5a1324ab6747.png)

![image](https://user-images.githubusercontent.com/65241877/102257966-6678b200-3f33-11eb-864d-83d5eea4905a.png)

Please help us get this resolved as this is impacting Aviation Migration.

**Comment by ayasuda-ge** [comment]
Thanks for the tracker @simran3695 @sheshankgujjari 

This issue has been identified and fixed. The unexpected exiting was caused by the unknown variables and has been fixed in [this commit](https://github.com/EC-Release/sdk/commit/5d43573d8b44c78fb9db04af552ea68666957936#diff-178f622634fcb61480724a7c7221a1e6cdab2c053171902beb15f28b66c070a2). The test result of the TLS plugin tcan be found in [this build](https://travis-ci.com/github/EC-Release/oci/jobs/460546104#L503)

The [latest update to this plugin](https://github.com/EC-Release/sdk/commit/9cf416b86696ecfebf843b363ce071fe4720e74d#diff-178f622634fcb61480724a7c7221a1e6cdab2c053171902beb15f28b66c070a2) is dated back to Oct-13-2020 and it was a non-functional update.

**Comment by ayasuda-ge** [comment]
Thanks for the tracker and helps in the debugging session @simran3695 

This issue has been identified and fixed. The unexpected exiting was caused by the unknown variables and has been fixed in [this commit](https://github.com/EC-Release/sdk/commit/5d43573d8b44c78fb9db04af552ea68666957936#diff-178f622634fcb61480724a7c7221a1e6cdab2c053171902beb15f28b66c070a2). The test result of the TLS plugin may be found in [this build](https://travis-ci.com/github/EC-Release/oci/jobs/460546104#L503)  @sheshankgujjari 


The [last update prior to this commit](https://github.com/EC-Release/sdk/commit/9cf416b86696ecfebf843b363ce071fe4720e74d#diff-178f622634fcb61480724a7c7221a1e6cdab2c053171902beb15f28b66c070a2) dated back to Oct-13-2020 and was a non-functional update.

**Comment by simran3695** [comment]
@ayasuda2OO3 The issue has been resolved and same has been tested.
