### ISSUE TITLE
EC connection issue with test connection for Azure EC Gateway

### ISSUE THREAD

**Issue by AakritiTalwar12** [EC-Release/oci#13]
Hi Team,

As discussed in the last call I am trying to connect an on cloud rds instance from my local.
Please find below the details of the connection

1. Client Agent - Running on my local machine.
2. Gateway - on Azure instance
3. Server Agent - Running on AWS EC2 instance.

I have verified the rds instance is reachable from the server agent machine.
while trying to connect I get pending confirmation from the gateway.
but cant get any log on the server side but super connection is intact all along
![Client logs](https://user-images.githubusercontent.com/58229454/83536658-23b03900-a511-11ea-95bd-dd11ade14343.PNG)
![Gateway Logs](https://user-images.githubusercontent.com/58229454/83536727-3c205380-a511-11ea-8076-4760270a31c1.PNG)
![Server logs](https://user-images.githubusercontent.com/58229454/83536744-43476180-a511-11ea-8a03-ef03e37fb2ad.PNG)

**Comment by ramaraosrikakulapu** [comment]
Hi @AakritiTalwar12 .. 

From the information given - 
- Server made successful super connection with gateway
- Client making call for transaction
- Client request reached to gateway VM via 'Azure App Gateway'
- Request is unable to forward to server agent (In fact request is not coming back to App gateway from Gateway VM)

Can you please confirm - 
- Reverify the target agent id in client script
- You are using ```hst``` url as ```ws://x.x.148.6/agent``` every where. 
- Can you please create and use load balancer instead of app gateway. Please refer  ```dc_ec_connectivity_test_LB``` in portal for load balancer settings ref.

@ayasuda2003 .. Yes, I reverified my settings and able to make connection via Azure gateway. Here is my use case with Azure gateway - 
- Run gateway in Azure VM behind Azure load balancer(Not 'Azure App Gateway')
- Run server agent in my machine in 'on prem' and connecting to mysql database
- For simplicity, I am running client also in 'on prem' but making connection via EC with ```localhost``` and ```lpt```
